version: '3.8'

services:
#   db:
#     image: postgres:15-alpine
#     container_name: pk-postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: ${DB_USER:-admin}
#       POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
#       POSTGRES_DB: ${DB_NAME:-parkirkampus}
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-parkirkampus}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

  redis:
    image: redis:7-alpine
    container_name: pk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata: